---
- name: Include OS specific variables
  include_vars: "{{ ansible_distribution | lower }}.yml"
- name: Check for homebrew installation on Mac
  stat:
    path: /usr/local/bin/brew
  register: brew
  changed_when: false
  when: ansible_distribution == "MacOSX"
- name: homebrew packages
  include_tasks: "system-packages-{{ ansible_distribution | lower }}-homebrew.yml"
  when: brew.stat is defined and brew.stat.exists
- name: shell configuration
  include_tasks: "shell-config-{{ ansible_user_shell | basename }}.yml"
- name: system package tasks
  include_tasks: "system-packages-{{ ansible_distribution | lower }}.yml"
- name: packer tasks
  include_tasks: packer-check.yml
- name: vagrant tasks
  include_tasks: vagrant-check.yml
- name: virtualbox tasks
  include_tasks: virtualbox-check.yml
