---
- name: Ensure packer build directory exists
  file:
    name: "{{ packer_build_dir }}"
    state: "directory"
    mode: 0700
- name: Ensure packer build files for VirtualBox have beein installed
  copy:
    dest: "{{ packer_build_dir }}/"
    src: virtualbox/{{ item }}
    mode: '0644'
  with_items:
    - answer_files
    - cookbooks
    - scripts
