---
- name: Ensure system brews are installed
  homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ system_brews }}"
  when:
    - system_brews is defined
    - (system_brews | length > 0)
- name: Ensure system casks are installed
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ system_casks }}"
  when:
    - system_casks is defined
    - (system_casks | length > 0)
- name: Ensure icons are added to the Dock
  shell: dockutil --find '{{ item.name }}' || dockutil -v --add '{{ item.path }}' --no-restart
  register: dockadd
  changed_when: "'item added at end' in dockadd.stdout"
  loop: "{{ dockitems_to_add }}"
  notify: launcher-restart-macosx
