---
# ==============
# virtualbox check
# ==============
# vars:
#   virtualbox_version: the targeted version of virtualbox
#   virtualbox_install_path: the directory containing the installed virtualbox
#
- name: Check if VBoxManage binary exists
  stat:
    path: "{{ virtualbox_install_path }}/VBoxManage"
  register: installed_virtualbox
  changed_when: false
- name: Check the version of VirtualBox if already installed
  command: "{{ virtualbox_install_path }}/VBoxManage --version"
  args:
    warn: false
  changed_when: false
  failed_when: false
  register: installed_virtualbox_version
  when:
    - installed_virtualbox.stat.exists
    - installed_virtualbox.stat.isreg
    - installed_virtualbox.stat.executable
- name: Install VirtualBox
  include_tasks: "virtualbox-install.yml"
  when: (not installed_virtualbox.stat.exists) or (installed_virtualbox_version.stdout is defined and installed_virtualbox_version.stdout != virtualbox_version_string)
