---
# Default variables assumed to be the same for all platforms are commented out
# but you can override them here if you want to test new software versions
# one platform at a time.
virtualization: virtualbox
#==============
#  Packer
#==============
#packer_version: "1.6.2"
#packer_bin: "packer"
#packer_install_path: "/usr/local/bin"
packer_zip: "packer_{{ packer_version }}_linux_amd64.zip"
packer_zip_url: "https://releases.hashicorp.com/packer/{{ packer_version }}/{{ packer_zip }}"
packer_zip_checksum: "sha256:089fc9885263bb283f20e3e7917f85bb109d9335f24d59c81e6f3a0d4a96a608"
#==============
#  Vagrant
#==============
#vagrant_version: "2.2.10"
#vagrant_bin: "vagrant"
#vagrant_install_path: "/usr/local/bin"
vagrant_package: "vagrant_{{ vagrant_version }}_x86_64.deb"
vagrant_package_url: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/{{ vagrant_package }}"
vagrant_package_checksum: "sha256:e770e3c6169ace1bdaed716cfbc084a2de2b0212a162303dffec6857a758b616"
#==============
#  Virtualbox
#==============
#virtualbox_short_version: "6.1"
#virtualbox_version: "6.1.14"
#virtualbox_build: "140239"
#virtualbox_install_path: "/usr/local/bin"
virtualbox_package: "virtualbox-{{ virtualbox_short_version }}_{{ virtualbox_version }}-{{ virtualbox_build }}~Debian~buster_amd64.deb"
virtualbox_package_url: "https://download.virtualbox.org/virtualbox/{{ virtualbox_version }}/{{ virtualbox_package }}"
virtualbox_package_checksum: "sha256:1d368820a4e2be8215df47b838cdc4430d108c8d29f94c77f89dff8c404ede4e"
