---
# Note:
# It is possible these values are overridden for specific
# platforms in ../vars/{{ ansible_distribution }}-vars.yml.
# ===========================================
# directories relative to the user's home dir
# ===========================================
downloads: "{{ ansible_user_dir }}/Downloads"
key_dir: "{{ ansible_user_dir }}/keys"
demo_root: "{{ ansible_user_dir }}/demo"
# ===========================================
# directories relative to the demo root dir
# ===========================================
packer_build_dir: "{{ demo_root }}/.setup/packer"
#==============
#  Packer
#==============
packer_version: "1.6.2"
packer_bin: "packer"
packer_install_path: "/usr/local/bin"
#==============
#  Vagrant
#==============
vagrant_version: "2.2.10"
vagrant_bin: "vagrant"
vagrant_install_path: "/usr/bin"
#==============
#  Virtualbox
#==============
virtualbox_short_version: "6.1"
virtualbox_version: "6.1.14"
virtualbox_build: "140239"
virtualbox_version_string: "{{ virtualbox_version }}r{{ virtualbox_build }}"
virtualbox_install_path: "/usr/bin"
