---
# study group specific
base_boxes:
  - name: "centos-8.2.2004"
    distro: "centos"
    version: "8.2.2004"
    guest_os_type: "RedHat_64"
    #iso_checksum: "sha256:c67876a5602faa17f68b40ccf2628799b87454aa67700f0f57eec15c6ccdd98c"
    iso_checksum: "sha256:c87a2d81d67bbaeaf646aea5bedd70990078ec252fc52f5a7d65ff609871e255"
    iso_location: "http://centos.s.uw.edu/centos/8.2.2004/isos/x86_64"
    #iso_name: "CentOS-8.2.2004-x86_64-boot.iso"
    iso_name: "CentOS-8.2.2004-x86_64-dvd1.iso"
    install_file: "centos-8.2.2004-ks.cfg"
    disk_size: "20480"
    ram: 1024
    template: "packer-centos.j2"
    templateks: "packer-centos-ks.j2"
# defaults for virtual network
virtual_networks:
  - name: 'RHCSA Network'
    netblock: '192.168.4.0/24'
  - name: 'RHCE Network'
    netblock: '192.168.5.0/24'
  - name: 'Network+ Network'
    netblock: '192.168.6.0/24'
